services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_API_URL=http://158.160.148.204:8080/api
        - NEXT_PUBLIC_SOCKET_URL=http://158.160.148.204:8080
    container_name: buddy-frontend
    environment:
      - NODE_ENV=production
      - PORT=3000
      - HOSTNAME=0.0.0.0
    ports:
      - "3000:3000"
    restart: unless-stopped
    networks:
      - buddy-network

networks:
  buddy-network:
    driver: bridge

